//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reminder.Storage.SqlServer.ADO.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reminder.Storage.SqlServer.ADO.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  insert into [Status] (name)
        /// values (&apos;Awaiting&apos;), (&apos;Ready&apos;),(&apos;Sent&apos;),(&apos;Failed&apos;)
        ///
        ///insert into Reminder (id, date, message, contact_id, status)
        ///values (&apos;00000000-0000-0000-0000-111111111111&apos;, &apos;2022-09-01 20:00:00.000&apos;, N&apos;Пора на рыбалку&apos;, &apos;contact_1&apos;, 0),
        ///		(&apos;00000000-0000-0000-0000-222222222222&apos;, &apos;2022-09-02 20:00:00.000&apos;, N&apos;Пора заняться программированием&apos;, &apos;contact_2&apos;, 0)
        ///.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IF EXISTS (SELECT * FROM sys.objects WHERE type = &apos;U &apos; AND name = &apos;Reminder&apos;)
        ///drop table dbo.Reminder
        ///go
        ///
        ///IF EXISTS (SELECT * FROM sys.objects WHERE type = &apos;U &apos; AND name = &apos;Status&apos;)
        ///drop table dbo.Status
        ///go
        ///
        ///create table [Status] (
        ///		id int identity(0,1), 
        ///		[name] varchar(32) not null,
        ///		constraint Pk_Status primary key clustered (id),
        ///		constraint Status_Unique unique ([name]))
        ///go
        ///
        ///create table Reminder (
        ///						id  uniqueidentifier,
        ///						--id  int identity(1,1),
        ///						date datetimeoffse [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Schema {
            get {
                return ResourceManager.GetString("Schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IF EXISTS (SELECT * FROM sys.objects WHERE type = &apos;P&apos; AND name = &apos;AddReminder&apos;)
        ///DROP PROCEDURE AddReminder
        ///
        ///go
        ///create procedure dbo.AddReminder(@id uniqueidentifier,
        ///								@date DateTimeOffset, 
        ///								@message nvarchar(max), 
        ///								@contactId nvarchar(max),
        ///								@status int)
        ///as
        ///begin
        ///	set nocount on
        ///
        ///	insert into Reminder (id, date, message, contact_id, status)
        ///	values (@id, @date, @message, @contactId, @status)
        ///end
        ///go
        ///.
        /// </summary>
        internal static string Stored_procedures {
            get {
                return ResourceManager.GetString("Stored_procedures", resourceCulture);
            }
        }
    }
}
